CREATE TABLE colors
(
    color_id    INTEGER NOT NULL,
    color_code  VARCHAR(3),
    color_label VARCHAR(255),
    color_hex   VARCHAR(7),
    CONSTRAINT pk_colors PRIMARY KEY (color_id)
);

CREATE TABLE images
(
    image_id        INTEGER      NOT NULL,
    image_url       VARCHAR(255) NOT NULL,
    widget_image_fk BIGINT       NOT NULL,
    CONSTRAINT pk_images PRIMARY KEY (image_id)
);

CREATE TABLE warehouse
(
    lot_number        INTEGER                     NOT NULL,
    created_at_date   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_edit         TIMESTAMP WITHOUT TIME ZONE,
    quantity          INTEGER                     NOT NULL,
    life_cycle_status VARCHAR(255)                NOT NULL,
    widget_id_fk      BIGINT                      NOT NULL,
    CONSTRAINT pk_warehouse PRIMARY KEY (lot_number)
);

CREATE TABLE widget_color
(
    color_id  INTEGER NOT NULL,
    widget_id BIGINT  NOT NULL,
    CONSTRAINT pk_widget_color PRIMARY KEY (color_id, widget_id)
);

CREATE TABLE widget_info
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    rating      FLOAT                                   NOT NULL,
    slug        VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_widget_info PRIMARY KEY (id)
);

ALTER TABLE images
    ADD CONSTRAINT FK_IMAGES_ON_WIDGET_IMAGE_FK FOREIGN KEY (widget_image_fk) REFERENCES widget_info (id);

ALTER TABLE warehouse
    ADD CONSTRAINT FK_WAREHOUSE_ON_WIDGET_ID_FK FOREIGN KEY (widget_id_fk) REFERENCES widget_info (id);

ALTER TABLE widget_color
    ADD CONSTRAINT fk_widcol_on_colors FOREIGN KEY (color_id) REFERENCES colors (color_id);

ALTER TABLE widget_color
    ADD CONSTRAINT fk_widcol_on_widget_info FOREIGN KEY (widget_id) REFERENCES widget_info (id);